" Use spaces instead of tabs
set expandtab
" Be smart when using tabs ;)
set smarttab
" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

set exrc
set relativenumber
set nu
set hidden
set smartcase

set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set scrolloff=4
set colorcolumn=80
set signcolumn=yes
set updatetime=50
set nocompatible
set exrc


call plug#begin('~/.vim/plugged')
    Plug 'gruvbox-community/gruvbox'
    Plug 'mbbill/undotree'
    Plug 'tpope/vim-fugitive'
    Plug 'nvim-lua/popup.nvim'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'
    if has('nvim')
        Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
        Plug 'neovim/nvim-lspconfig'
    else
    endif
call plug#end()



colorscheme gruvbox
set bg=dark
let mapleader = " "

nnoremap <leader>wo :only<cr>
nnoremap <leader>fg :Ack

nnoremap <leader>ff <cmd>Telescope git_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>

nnoremap <leader>fh <cmd>Telescope command_history<cr>
nnoremap <leader>fH <cmd>Telescope help_tags<cr>


nnoremap <leader>fg <cmd>Telescope help_tags<cr>
if executable('rg')
  let g:ackprg = 'rg --vimgrep --smart-case'
endif

if has('nvim')
          
    set completeopt=menuone,noinsert,noselect

    nnoremap <leader>vd :lua vim.lsp.buf.definition()<CR>
    nnoremap <leader>vi :lua vim.lsp.buf.implementation()<CR>
    nnoremap <leader>vsh :lua vim.lsp.buf.signature_help()<CR>
    nnoremap <leader>vrr :lua vim.lsp.buf.references()<CR>
    nnoremap <leader>vrn :lua vim.lsp.buf.rename()<CR>
    nnoremap <leader>vh :lua vim.lsp.buf.hover()<CR>
    nnoremap <leader>vca :lua vim.lsp.buf.code_action()<CR>
    nnoremap <leader>vsd :lua vim.lsp.util.show_line_diagnostics(); vim.lsp.util.show_line_diagnostics()<CR>

    let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
    lua require'lspconfig'.tsserver.setup{ on_attach=require'completion'.on_attach }
    lua require'lspconfig'.clangd.setup{ on_attach=require'completion'.on_attach }
    lua require'lspconfig'.pyls.setup{ on_attach=require'completion'.on_attach }
    lua require'lspconfig'.gopls.setup{ on_attach=require'completion'.on_attach }
    lua require'lspconfig'.rust_analyzer.setup{ on_attach=require'completion'.on_attach }
    " lua require'nvim_lsp'.sumneko_lua.setup{ on_attach=require'completion'.on_attach }
endif

" Delete trailing white space on save, useful for some filetypes ;)
function! TrimTrailingWhitespace()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfunction

command! -bang Trimtrailingwhitespace call TrimTrailingWhitespace()

nnoremap <silent> <leader>s1 : call CreateSession('s1') <cr>
nnoremap <silent> <leader>s2 : call CreateSession('s2') <cr>
nnoremap <silent> <leader>s3 : call CreateSession('s3') <cr>
nnoremap <silent> <leader>s4 : call CreateSession('s4') <cr>
nnoremap <silent> <leader>s5 : call CreateSession('s5') <cr>

function! CreateSession(sessionName)
    exe "mks! ". a:sessionName
    echo "created session ". a:sessionName
endfunction



function! CscopeDone()
	exe "cs add cscope.out"
endfunc

function! CscopeUpdate()
	try | exe "cs kill cscope.out" | catch | endtry
	exe "AsyncRun -post=call\\ g:CscopeDone() ".
                \ "git ls-files >cscope.files && ".
				\ "cscope -bi cscope.files"
endfunction

command! CscopeUpdate call CscopeUpdate()
