#!/bin/bash
if [ -x "$(command -v nvim)" ]; then
    nvim='nvim'
else
    nvim='vim'
fi

param=""
session=$(ls -t| grep -e '^s[0-9]$' | head -n 1)
if [ ! -z $session ]; then
    param="-S $session"
fi
$nvim $param
